# Taps
tap 'hashicorp/tap'
tap 'go-task/tap'
tap 'oven-sh/bun'

# Binaries
brew 'bash' # Latest Bash version
brew 'bat'
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'git-lfs'
brew 'grep'
brew 'wget'
brew 'jq'
brew 'mackup'
brew 'mas' # Mac App Store manager
brew 'svn' # Needed to install fonts
brew 'go'

# Development
cask 'iterm2'
brew 'nvm'
brew 'pyenv'
brew 'ruby-build'
brew 'rbenv'
brew 'firebase-cli'
cask 'gcloud-cli'
brew 'azure-cli'
brew 'docker-compose'
brew 'graphviz'
brew 'fastlane'
brew 'hashicorp/tap/terraform'
brew 'gnupg'
brew 'lazygit'
brew 'apktool'
brew 'htop'
brew 'kdoctor'
brew 'pdm'
brew 'rsync'
brew 'go-task/tap/go-task'
brew 'goose'
brew 'uv'
brew 'helm'
brew 'watch'
brew 'postgresql'
brew 'k9s'
brew 'opentofu'
brew 'ack'
brew 'oven-sh/bun/bun'
brew 'anomalyco/tap/opencode'
brew 'kotlin'
brew 'pure'
brew 'z'
brew 'colima'
brew 'mise'

# Apps
cask 'caffeine'
cask 'discord'
cask 'docker-desktop'
cask 'google-chrome'
cask 'visual-studio-code'
cask 'flutter'
cask 'spotify'
cask 'jetbrains-toolbox'
cask 'transmission'
cask 'rectangle'
cask 'keka'
cask 'bruno'
cask 'yubico-authenticator'
cask 'obsidian'
cask 'mitmproxy'
cask 'vlc'
cask 'scroll-reverser'
cask 'dbeaver-community'
cask 'opencode-desktop'
cask '1password-cli'

# Fonts
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-3'
cask 'font-source-serif-4'
cask 'font-fira-code'
cask 'font-fira-mono'

# Mac App Store
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'Xcode', id: 497799835
